// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Papeleria.Data;

#nullable disable

namespace Papeleria.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905001545_ReferenciaDePagoYBilleteras")]
    partial class ReferenciaDePagoYBilleteras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Papeleria.Domain.Entities.AbonoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("CajaSesionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaSesionId")
                        .HasDatabaseName("IX_AbonosCliente_CajaSesionId");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_AbonosCliente_ClienteId");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_AbonosCliente_Fecha");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AbonosCliente", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.CajaSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diferencia")
                        .HasColumnType("REAL");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("MontoEsperado")
                        .HasColumnType("REAL");

                    b.Property<double>("MontoInicial")
                        .HasColumnType("REAL");

                    b.Property<double>("MontoReal")
                        .HasColumnType("REAL");

                    b.Property<string>("ObservacionesApertura")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalEgresos")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalIngresos")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalVentasEfectivo")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalVentasOtros")
                        .HasColumnType("REAL");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_CajaSesiones_Estado");

                    b.HasIndex("FechaApertura")
                        .HasDatabaseName("IX_CajaSesiones_FechaApertura");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("CajaSesiones", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Nombre");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsProtegido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Clientes_Nombre");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_NumeroDocumento");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacturaProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalIva")
                        .HasColumnType("REAL");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Compras_Fecha");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Compras_Numero");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("IX_Compras_ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.CompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostoUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("PorcentajeDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("PorcentajeIva")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorIva")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CompraId")
                        .HasDatabaseName("IX_CompraDetalles_CompraId");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_CompraDetalles_ProductoId");

                    b.ToTable("CompraDetalles", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("IX_Configuraciones_Clave");

                    b.ToTable("Configuraciones", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaSesionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostoTotal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaSesionId")
                        .HasDatabaseName("IX_Devoluciones_CajaSesionId");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Devoluciones_Fecha");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Devoluciones_Numero");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("IX_Devoluciones_VentaId");

                    b.ToTable("Devoluciones", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.DevolucionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<double>("CostoUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DevolucionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DevolucionId")
                        .HasDatabaseName("IX_DevolucionDetalles_DevolucionId");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_DevolucionDetalles_ProductoId");

                    b.ToTable("DevolucionDetalles", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Marcas_Nombre");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AfectaEfectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("CajaSesionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaSesionId")
                        .HasDatabaseName("IX_MovimientosCaja_CajaSesionId");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_MovimientosCaja_Fecha");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_MovimientosCaja_Tipo");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.MovimientoKardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<double>("CostoUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Salida")
                        .HasColumnType("REAL");

                    b.Property<double>("StockAnterior")
                        .HasColumnType("REAL");

                    b.Property<double>("StockNuevo")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_MovimientosKardex_Fecha");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_MovimientosKardex_ProductoId");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_MovimientosKardex_Tipo");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProductoId", "Fecha")
                        .HasDatabaseName("IX_MovimientosKardex_Producto_Fecha");

                    b.ToTable("MovimientosKardex", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.PermisoRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Rol", "Modulo")
                        .IsUnique()
                        .HasDatabaseName("IX_Permisos_Rol_Modulo");

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenPath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<double>("PorcentajeIva")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("REAL");

                    b.Property<double>("StockActual")
                        .HasColumnType("REAL");

                    b.Property<double>("StockMaximo")
                        .HasColumnType("REAL");

                    b.Property<double>("StockMinimo")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnidadesPorPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Productos_Activo");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Productos_CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Productos_Codigo");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("IX_Productos_CodigoBarras");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("IX_Productos_MarcaId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Productos_Nombre");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Productos_Tipo");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacto")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("IX_Proveedores_Nit");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Proveedores_Nombre");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_UnidadesMedida_Nombre");

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsProtegido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_NombreUsuario");

                    b.HasIndex("Rol")
                        .HasDatabaseName("IX_Usuarios_Rol");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaSesionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cambio")
                        .HasColumnType("REAL");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MontoRecibido")
                        .HasColumnType("REAL");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalIva")
                        .HasColumnType("REAL");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaSesionId")
                        .HasDatabaseName("IX_Ventas_CajaSesionId");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Ventas_ClienteId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Ventas_Estado");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Ventas_Fecha");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("IX_Ventas_NumeroFactura");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<double>("CostoUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("PorcentajeDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("PorcentajeIva")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorIva")
                        .HasColumnType("REAL");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_VentaDetalles_ProductoId");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("IX_VentaDetalles_VentaId");

                    b.ToTable("VentaDetalles", (string)null);
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.AbonoCliente", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.CajaSesion", "CajaSesion")
                        .WithMany()
                        .HasForeignKey("CajaSesionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papeleria.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaSesion");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.CajaSesion", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Usuario", "UsuarioApertura")
                        .WithMany()
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Compra", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.CompraDetalle", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Producto", "Producto")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Devolucion", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.CajaSesion", "CajaSesion")
                        .WithMany()
                        .HasForeignKey("CajaSesionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaSesion");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.DevolucionDetalle", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Devolucion", "Devolucion")
                        .WithMany("Detalles")
                        .HasForeignKey("DevolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devolucion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.CajaSesion", "CajaSesion")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CajaSesion");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.MovimientoKardex", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Producto", "Producto")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papeleria.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Venta", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.CajaSesion", "CajaSesion")
                        .WithMany("Ventas")
                        .HasForeignKey("CajaSesionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papeleria.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaSesion");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.VentaDetalle", b =>
                {
                    b.HasOne("Papeleria.Domain.Entities.Producto", "Producto")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papeleria.Domain.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.CajaSesion", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Devolucion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Producto", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("MovimientosKardex");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("MovimientosKardex");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Papeleria.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
